CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(30) NOT NULL UNIQUE PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );


CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    agent_name TEXT NOT NULL,
    username VARCHAR(30) NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    product VARCHAR(255) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    status VARCHAR(50) DEFAULT 'pending',
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS chat (
    id SERIAL PRIMARY KEY,
    agent_name TEXT NOT NULL,
    username VARCHAR(30) NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    chat_id INT REFERENCES chat(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    sender TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS complaints (
    id SERIAL PRIMARY KEY,
    agent_name TEXT NOT NULL,
    username VARCHAR(30) NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    complaint TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );


CREATE INDEX IF NOT EXISTS idx_order_date ON orders (order_date);
